package com.ruoyi.business.entity;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class SaleOrderEntry {

    /** 明细主键 */
    private Long fEntryId;
    /** 销售订单FID */
    private String fbillNo;
    /** 包材有库存 */
    private String fBcykc;

    /** 产品类别 */
    private String fSfxp;
    /** 交期红线 */
    private Date fJqhx;
    /** 物料编码 */
    private String fPlanMaterialId;
    /** 物料名称 */
    private String fPlanMaterialName;
    /** 英文描述 */
    private String fCtyBaseProperty2;
    /** 销售单位 */
    private String fPlanUnitId;
    /** 销售数量 */
    private BigDecimal fQty;
    /** 计价数量 */
    private BigDecimal fMaterialPriceUnitQty;
    /** 计价单位 */
    private String fMaterialPriceUnitID;
    /** 单价 */
    private BigDecimal fPrice;
    /** 含税单价 */
    private BigDecimal fTaxPrice;
    /** 税率% */
    private BigDecimal fEntryTaxRate;
    /** 税额 */
    private BigDecimal fEntryTaxAmount;
    /** 价税合计 */
    private BigDecimal fAllAmount;
    /** 可出数量（销售基本） */
    private BigDecimal fBaseCanOutQty;
    /** 累计发货通知数量 */
    private BigDecimal fDeliQty;
    /** 可出数量（库存基本） */
    private BigDecimal fStockBaseCanOutQty;
    /** 客户货号 */
    private String fOraText1;
    /** 发货日期 */
    private Date fOraDate3;
    /** 负责人 */
    private String fFzr;
    /** 采购合同号 */
    private String fOraText;
    /** 供应商实际完成订单日期 */
    private Date fOraDate1;
    /** 实际收货日期 */
    private Date fOraDate2;
    /** 关联采购/生产数量 */
    private BigDecimal fPurJoinQty;
    /** 延迟原因 */
    private String fOraBase1;
    /** 延迟解决方案 */
    private String fYcjjfa;
    /** 采购价 */
    private BigDecimal fOraDecimal;
    /** 业务员提供包装资料日期 */
    private Date fOraDate4;
    /** 成本价 */
    private BigDecimal fOraDecimal1;
    /** 包装资料晚交天数 */
    private Integer fOraInteger2;
    /** 包装寄出日期 */
    private Date fOraDate5;
    /** 包装寄出延迟天数 */
    private Integer fOraInteger3;
    /** 包装进度 */
    private String fBzjdTwo;
    /** 供应商 */
    private String fOraBase;
    /** 工厂交货期 */
    private Integer fOraInteger;
    /** 采购合同日期 */
    private Date fOraDate;
    /** 毛重 */
    private BigDecimal fmz;
    /** 净重 */
    private BigDecimal fjz;
    /** 毛总重 */
    private BigDecimal fmzz;
    /** 装箱数 */
    private Integer fzxs;
    /** 箱数 */
    private Integer fxs;
    /** 跟单图片1 */
    private String fGdtp1;
    /** 跟单图片2 */
    private String fGdtp2;
    /** 跟进情况 */
    private String fXdgjjdTwo;
    /** 包装要求 */
    private String fBzfs;
    /** 特殊要求 */
    private String fTsyq;
    /** 累计入库数量 */
    private BigDecimal fljrksl;
    /** 颜色标识 */
    private String fYsbz;
    /** 变更日期 */
    private Date fBgrq;
    /** 彩贴图 */
    private String fCtt;
    /** 产品图片 */
    private String fCptp;
    /** 工厂包装 */
    private String fGcbz;
    /** 货好未入库 */
    private Boolean fHhwrk;
    /** 开票单价 */
    private BigDecimal fKpdj;
    /** 包装下单状态 */
    private String fBzxdzt;
    /** 更新状态 */
    private String fGxzt;
    /** 彩盒图 */
    private String fCht;
    /** 禁告贴 */
    private String fjgt;
    /** 说明书附件 */
    private String fSmsfj;
    /** 包材获取状态 */
    private String fBchqzt;
    /** 退税率% */
    private BigDecimal fTsl;
    /** 报关英文品名 */
    private String fBgywpm;
    /** 报关单位 */
    private String fBgdw;
    /** 实际成本 */
    private BigDecimal fYgcb;
    /** HS编码 */
    private String fHsbm;
    /** 申报要素 */
    private String fSbys;
    /** 包材费用 */
    private BigDecimal fBcfyNew;
    /** 关联包材费用 */
    private BigDecimal fGlbcfyNew;
    /** 包装尺寸 */
    private String fbzcc;
    /** 包装工厂提供 */
    private Boolean fbzgctg;
    /** 入库审核日期 */
    private Date frkshrq;
    /** 报价人 */
    private String fBjr;
    /** 推品人 */
    private String fTpr;
    /** 修改状态 */
    private String fCtyBaseProperty4;
    /** 客户英文描述 */
    private String fKhywms;
    /** 延迟原因 */
    private String fCtyBaseProperty6;
    /** 实际成本单价 */
    private BigDecimal fYgcbdj;
    /** 预估成本单价 */
    private BigDecimal fYgcbdj1;
    /** 预估成本 */
    private BigDecimal fYgcb1;
    /** 验货报告 */
    private String fPeuuAttachment83g;
    /** 采购订单审核日期 */
    private Date fCgddshrq;
    /** 预警时间 */
    private Date fYjsj;
    /** 收料审核日期 */
    private Date fSlshrq;
    /** 新老产品 */
    private String fXlcp;
    /** 产品大类 */
    private String fCplb;
    /** 出库日期 */
    private Date fCkrq;
    /** 供应商评级 */
    private String fCtyBaseProperty7;
    /** 工厂问题 */
    private String fCtyBaseProperty8;
}
