-- ERP Public Configuration Management - Menu Initialization SQL
-- Generated by PowerShell Script
-- Timestamp: 2026-03-25 05:12:10

USE test;

-- Create parent menu (ERP Business Menu)
SET @erp_parent_id := '1943362205047062529';
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, remark, create_by, create_time)
SELECT @erp_parent_id, 'ERP 业务菜单' COLLATE utf8mb4_general_ci, 
       0, 5, 'business', '', 0, 0, 'M', 1, 1, '', 'document', 
       'ERP 业务菜单目录', 'admin', NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM sys_menu WHERE menu_name COLLATE utf8mb4_general_ci = 'ERP 业务菜单' COLLATE utf8mb4_general_ci
);

-- Create config management menu
SET @config_menu_id := '162307528422595391';
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query_param, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT @config_menu_id, '公共配置管理' COLLATE utf8mb4_general_ci, @erp_parent_id, 2, 'erp/config', 
        'erp/config/index', '{"moduleCode":"erp"}', 0, 0, 'C', 1, 1, 
        'erp:config:query', 'setting', 'admin', NOW(), '', NULL, 'ERP 公共配置管理页面'
WHERE NOT EXISTS (
    SELECT 1 FROM sys_menu 
    WHERE menu_name COLLATE utf8mb4_general_ci = '公共配置管理' COLLATE utf8mb4_general_ci
    AND parent_id = @erp_parent_id
);

-- Create button permissions using temporary table
CREATE TEMPORARY TABLE IF NOT EXISTS tmp_config_buttons (
    menu_id VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    menu_name VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    parent_id BIGINT,
    order_num INT,
    perms VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    status CHAR(1) DEFAULT '1'
) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DELETE FROM tmp_config_buttons;

INSERT INTO tmp_config_buttons (menu_id, menu_name, parent_id, order_num, perms, status) VALUES
('162307528556811169', '查询' COLLATE utf8mb4_general_ci, @config_menu_id, 1, 'erp:config:query', '1'),
('162307528691027309', '新增' COLLATE utf8mb4_general_ci, @config_menu_id, 2, 'erp:config:add', '1'),
('162307528825249215', '修改' COLLATE utf8mb4_general_ci, @config_menu_id, 3, 'erp:config:edit', '1'),
('162307528959461983', '删除' COLLATE utf8mb4_general_ci, @config_menu_id, 4, 'erp:config:remove', '1'),
('162307529093684216', '导出' COLLATE utf8mb4_general_ci, @config_menu_id, 5, 'erp:config:export', '1'),
('9223372034707304446', '导入' COLLATE utf8mb4_general_ci, @config_menu_id, 6, 'erp:config:import', '1'),
('9223372034841518063', '复制' COLLATE utf8mb4_general_ci, @config_menu_id, 7, 'erp:config:copy', '1'),
('9223372034975730623', '历史版本' COLLATE utf8mb4_general_ci, @config_menu_id, 8, 'erp:config:history', '1'),
('9223372035109954046', '回滚' COLLATE utf8mb4_general_ci, @config_menu_id, 9, 'erp:config:rollback', '1'),
('9223372035244165085', '状态管理' COLLATE utf8mb4_general_ci, @config_menu_id, 10, 'erp:config:status', '1');

INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query_param, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT t.menu_id, t.menu_name COLLATE utf8mb4_general_ci, @config_menu_id, t.order_num, '', '', '', 0, 0, 'F', 1, 1, t.perms COLLATE utf8mb4_general_ci, '#', 'admin', NOW(), '', NULL, ''
FROM tmp_config_buttons t
WHERE NOT EXISTS (
    SELECT 1 FROM sys_menu s 
    WHERE s.menu_name COLLATE utf8mb4_general_ci = t.menu_name COLLATE utf8mb4_general_ci
    AND s.parent_id = @config_menu_id
);

DROP TEMPORARY TABLE IF EXISTS tmp_config_buttons;

-- Verification queries
SELECT '===== Menus =====' AS section;
SELECT menu_id, menu_name, parent_id, path, menu_type, visible, status, perms
FROM sys_menu WHERE menu_id IN (@erp_parent_id, @config_menu_id) ORDER BY parent_id;

SELECT '===== Buttons =====' AS section;
SELECT menu_id, menu_name, parent_id, perms, status
FROM sys_menu WHERE menu_type = 'F' AND parent_id = @config_menu_id ORDER BY order_num;

SELECT '========================================' AS '';
SELECT '✅ ERP Configuration Menu Created Successfully!' AS message;
SELECT '========================================' AS '';